spring:
  datasource:
    url: jdbc:h2:file:./testdb3;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;OLD_INFORMATION_SCHEMA=TRUE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: "/static/**"
logging:
  level:
    org.hibernate.SQL: debug
