spring:
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
#
#server:
#  ssl:
#    enabled: true
#    key-store: classpath:static/apikey.jks
#    key-password: 1q2w3e4r!
#    key-store-type: PKCS12
#    key-alias: apple
#    trust-store-password: 1q2w3e4r!
#    key-store-password: 1q2w3e4r!


